import { BitacoraOptions } from "../types/bitacora";



export const bitOpts: Record<string, BitacoraOptions> = {


  reports: {
    tabla: "reports",
    idColumn: "id_report",
    idParam: "id",
    modulo: "Reportes",
    fields: ["id_report","tipo","periodo","fecha","estado"],
  },
  users: {
    tabla: "users",
    idColumn: "id_user",
    idParam: "id",
    modulo: "Usuarios",
    fields: ["id_user","username","email","password","estado","password"],
  },
  roles: {
    tabla: "roles",
    idColumn: "id_rol",
    idParam: "id",
    modulo: "Roles",
    fields: ["id_rol","name","description","estado"],
  },
  employes: {
    tabla: "employes",
    idColumn: "id_employes",
    idParam: "id",
    modulo: "Empleados",
    fields: ["name","email","telefono","puesto","estado"],
  },
  units: {
    tabla: "units",
    idColumn: "id_units",
    idParam: "id",
    modulo: "Unidades",
    fields: ["name","estado"],
  },
  pacts: {
    tabla: "pacts",
    idColumn: "id_pacts",
    idParam: "id",
    modulo: "Pactos",
    fields: ["name","tipo","estado"],
  },
  kardex: {
    tabla: "Kardex",
    idColumn: "id_kardex",
    idParam: "id",
    modulo: "Kardex",
    fields: ["id_kadex",
      "id_product",
      "id_shopping",
      "anio_creacion",
      "tipo_movimiento",
      "fecha_movimiento",
      "numero_factura",
      "cantidad",
      "precio_unitario",
      "tipo_solicitud",
      "requisicion_numero",
      "tipo",
      "observacion",
      "estado"],
  },
  shopping: {
    tabla: "shopping",
    idColumn: "id_shopping",
    idParam: "id",
    modulo: "Compras",
    fields: ["id_vendedor","total","fecha_compra","estado"],
  },
  product: {
    tabla: "product",
    idColumn: "id_product",
    idParam: "id",
    modulo: "Productos",
    fields: ["nombre",
      "descripcion",
      "stock_actual",
      "stock_maximo",
      "fecha_vencimiento",
      "numero_lote",
      "estado"],  
  },
  category: {
    tabla: "category",
    idColumn: "id_category",
    idParam: "id",
    modulo: "Categoria",
    fields: ["name","descripcion","estado"],
  },
  subcategory: {
    tabla: "subcategory",
    idColumn: "id_subcategory",
    idParam: "id",
    modulo: "Subcategorías",
    fields: ["name","estado"],
  },
  units_x_pacts: {
    tabla: "units_x_pacts",
    idColumn: "id_units_x_pacts",
    idParam: "id",
    modulo: "UnidadesPactos",
    fields: ["id_units","id_pacts", "id_subcategory","cantidad","estado"],
  },
  noti: {
    tabla: "notifications",
    idColumn: "id_noti",
    idParam: "id",
    modulo: "Notificaciones",
    fields: ["id_user","mensaje","tipo","estado"],
  },
  requisi: {
    tabla: "requisitions",
    idColumn: "id_requisi",
    idParam: "id",
    modulo: "Requisiciones",
    fields: ["id_employes","fecha","tipo"],
  },
  scompras: {
    tabla: "solicitud_compras",
    idColumn: "id_scompra",
    idParam: "id",
    modulo: "SolicitudesCompras",
    fields: ["id_scompra","id_requisi","estado"],
  },
  vendedor: {
    tabla: "vendedor",
    idColumn: "id_vendedor",
    idParam: "id",
    modulo: "Vendedores",
    fields: ["id_vendedpor","nombre_contacto","correo","estado"],
  },
  supplier: {
    tabla: "suppliers",
    idColumn: "id_supplier",
    idParam: "id",
    modulo: "Proveedores",
    fields: ["nombre","numero_contacto","correo","estado"],
  },
   subdireccion: {
    tabla: "subdireccion",
    idColumn: "id_subdireccion",
    idParam: "id",
    modulo: "Subdireccion",
    fields: ["nombre","estado"],
  },
    requiXproduct: {
    tabla: "Requi_x_Product",
    idColumn: "id_requisi_x_product",
    idParam: "id",
    modulo: "Requisicion_x_Producto",
    fields: ["id_requisi_x_product","id_requisi","id_product","cantidad","estado"],
  },
  direction: {
  tabla:    "direction",
  idColumn: "id_direction",
  idParam:  "id_",
  modulo:   "Direccion",
  fields:   ["nombre","estado"],
},
  biracora: {
    tabla: "bitacora",
    idColumn: "id",
    idParam: "id",
    modulo: "Bitacora",
    fields: ["nombre","estado"],
  },
  donantes: {
    tabla: "donantes",
    idColumn: "id_donante",
    idParam: "id",
    modulo: "Donantes",
    fields: ["nombre", "tipo_donante", "numero_contacto", "correo", "direccion", "rtn", "notas", "estado"],
  },
};
