# .github/workflows/pr-test.yml
name: PR Test Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Mostrar mensaje de prueba
        run: |
          echo "✅ GitHub Action ejecutada correctamente!"
          echo "Pull Request creado por: ${{ github.actor }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "Número de PR: #${{ github.event.pull_request.number }}"
